name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
            - '8.4'
            - '8.5'

    name: PHP ${{ matrix.php-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"

      - name: Check composer.json normalization
        run: composer normalize --diff --dry-run

      - name: Check README examples are in sync
        run: |
          vendor/bin/readme-examples-sync
          git diff --exit-code README.md || (echo "README.md is out of sync with example files. Run 'vendor/bin/readme-examples-sync' and commit the changes." && exit 1)

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer check --diff
